config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :channels do
    resource :channel_user
    resources :messages
  end
  devise_for :users
  ActiveAdmin.routes(self)
  root 'movies#index'
  resources :movies, only: %i[index show] do
    resources :reviews
    member do
      put 'like' => 'movies#upvote'
      put 'dislike' => 'movies#downvote'
    end
  end
  get 'favorite/:id' => 'favorites#show', as: 'favorite'
  delete 'favorite/:id' => 'favorites#destroy'
  post 'line_items' => 'line_items#create'
  get 'line_items/:id' => 'line_items#show', as: 'line_item'
  delete 'line_items/:id' => 'line_items#destroy'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :movies
  validates :genre, uniqueness: true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :channel_users, dependent: :destroy
  has_many :users, through: :channel_users
  has_many :messages, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: :user_id

  validates :name, presence: true, length: { maximum: 18 }, uniqueness: true
  validates :author, presence: true
  validate :author_channel_count

  def author_channel_count
    errors.add(:name, 'Не больше 6 созданных каналов на пользователя.') if author.channel_author.count > 6
  end
end

app/models/channel_user.rb
class ChannelUser < ApplicationRecord
  belongs_to :channel
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :movies, through: :line_items
  belongs_to :user, optional: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :movie
  belongs_to :favorite
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  # before_save :parse_kinopoisk, on: :create
  before_save :add_categories_to_movie, :default_values

  has_and_belongs_to_many :categories, dependent: :destroy
  has_many :line_items, dependent: :destroy
  has_many :favorites, through: :line_items
  has_many :reviews, dependent: :destroy

  validates :global_id, uniqueness: true, presence: true
  # validates :title_ru, presence: true
  # validates :title_en, presence: true
  # validates :country, presence: true
  # validates :year, presence: true

  acts_as_votable

  def add_categories_to_movie
    genre.downcase!
    genre.split(', ').each do |kinopoisk_genre|
      category = Category.find_by(genre: kinopoisk_genre)
      next if category.blank?

      categories << category unless categories.any? { |x| x.genre == category.genre }
    end
  end

  def default_values
    self.like ||= 0
    self.dislike ||= 0
  end

  def self.first_start(limit = nil)
    Category.create!([
                       { genre: 'биография' },
                       { genre: 'боевик' },
                       { genre: 'вестерн' },
                       { genre: 'военный' },
                       { genre: 'детектив' },
                       { genre: 'документальный' },
                       { genre: 'драма' },
                       { genre: 'исторический' },
                       { genre: 'комедия' },
                       { genre: 'криминал' },
                       { genre: 'мелодрама' },
                       { genre: 'мультфильм' },
                       { genre: 'приключения' },
                       { genre: 'сериал' },
                       { genre: 'спорт' },
                       { genre: 'триллер' },
                       { genre: 'ужасы' },
                       { genre: 'фантастика' },
                       { genre: 'фентези' }
                     ])

    require 'json'

    file = File.read(File.join(Rails.root, 'db', 'lordfilm.json'))
    data = JSON.parse(file).take(limit) if limit.present?
    data = data.take(limit) if limit.present?
    data.each do |movie|
      Movie.create(
        global_id: movie['kp_id'],
        title_ru: movie['title_ru'],
        title_en: movie['title_en'],
        year: movie['year'],
        acter: movie['actors'].join(', '),
        producer: movie['producer'],
        country: movie['country'].join(', '),
        genre: movie['genre'].join(', '),
        description: movie['about'],
        image_link: movie['poster']
      )
    end
  end

  #
  #     def parse_kinopoisk
  #       film = KpApi::Film.new(self.global_id)
  #       acter_arr = Array.new
  #       producer_arr = Array.new
  #
  #       film.peoples_full.each do |people|
  #         if people.has_value?("Режиссеры") && producer_arr.size < 5 # поиск режиссёра
  #           producer_arr << people[:name_ru]
  #         end
  #         if people.has_value?("Актеры") && acter_arr.size < 10 # поиск актёров
  #           acter_arr << people[:name_ru]
  #         end
  #       end
  #
  #       self.title_ru = film.view[:name_ru].downcase if self.title_ru.blank?
  #       self.title_en = film.view[:name_en].downcase if self.title_en.blank?
  #       self.country = film.view[:countries].map {|country| %Q(#{country})}.join(", ") if self.country.blank?
  #       self.genre = film.view[:genres].map {|genre| %Q(#{genre})}.join(", ") if self.genre.blank?
  #       self.duration = film.view[:duration] if self.duration.blank?
  #       self.description = film.view[:description] if self.description.blank?
  #       self.producer = producer_arr.map {|a| %Q(#{a})}.join(", ") if self.producer.blank?
  #       self.acter = acter_arr.map {|a| %Q(#{a})}.join(", ") if self.acter.blank?
  #       self.year = film.view[:year] if self.year.blank?
  #       self.image_link = film.view[:poster_url] if self.image_link.blank?
  #       self.like = (film.view[:rating_film_critics_vote_count].to_f/100*film.view[:rating_film_critics].to_f).to_i if self.like.blank?
  #       self.dislike = film.view[:rating_film_critics_vote_count]-(film.view[:rating_film_critics_vote_count].to_f/100*film.view[:rating_film_critics].to_f).to_i if self.dislike.blank?
  #
  #       film.view[:genres].each do |kinopoisk_genre|
  #         category = Category.find_by(genre: kinopoisk_genre)
  #         if category.blank?
  #           next
  #         end
  #         unless self.categories.any?{|x| x.genre == category.genre}
  #           self.categories << category
  #         end
  #       end
  #     end
  # end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :body, :user, :movie, presence: true, length: { maximum: 256 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :favorite
  has_many :channel_users, dependent: :destroy
  has_many :channels, through: :channel_users
  has_many :channel_author, class_name: 'Channel', foreign_key: :user_id, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :reviews, dependent: :destroy
  def account_active?
    !blocked
  end

  def active_for_authentication?
    super && account_active?
  end

  def inactive_message
    account_active? ? super : :locked
  end
end

app/models/voter_session.rb
class VoterSession < ApplicationRecord
  acts_as_voter
end

app/helpers/application_helper.rb
module ApplicationHelper
  def favorite_include_movie?(movie)
    @favorite.line_items.map { |line_item| line_item.movie.id }.include?(movie.id)
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def genre_link(movie)
    valid_genre = movie.categories.map do |genre_object|
      link_to(genre_object.genre.to_s, movies_path(category: genre_object))
    end
    no_valid_genre = movie.genre.split(', ') - movie.categories.map { |genre_object| genre_object.genre }
    (valid_genre + no_valid_genre).join(', ').html_safe
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, msg| %>
 <% if key == "notice" %>
    <div class="alert alert-info" id="flash"><%= msg %></div>
    <% elsif key == "alert" || key == "danger" %>
    	<div class="alert alert-danger" id="flash"><%= msg %></div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ddm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Russo+One" rel="stylesheet">
  </head>

  <body>
     <header>
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark rounded">
          <%=link_to "DDM", root_path, class:"navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fa fa-bars"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample09">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to "Закладки (#{@favorite.line_items.count})", favorite_path(@favorite), class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Чат киноманов", channels_path, class:"nav-link" %>
              </li>
            </ul>
            <%= render 'search/form' %>
             <% if user_signed_in? %>
                <span class="navbar-brand navbar-username"><%= current_user.username%></span>
                  <span class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown"></a>
                        <ul class="dropdown-menu customdrop customnav">
                          <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
                          <li><%= link_to 'Изменить профиль', edit_user_registration_path %> </li>
                          <% if current_user.admin %>
                            <li><%= link_to 'Панель админа', admin_root_path %>
                          <% end %>
                        </ul>
                    </span>
                <% else %>
                    <span class="dropdown customnav navbar-username">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Вход <b class="caret"></b></a>
                        <ul class="dropdown-menu customdrop customnav">
                            <li><%= link_to 'Войти', new_user_session_path %> </li>
                            <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
                        </ul>
                    </span>
                <% end %>
          </div>
        </nav>
      </div>
    </header>
    <div class="container custom-container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>